name: Update README with Repos

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:       # allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List repositories
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: KurchetiGurubhaskar
          repo: KurchetiGurubhaskar
          path: README.md
          start: repos
          end: repos
          max: 10
          commit-message: "Update README with latest repositories"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest repositories"
          git push
